Add contact section
devMunyi/Portfolio pull request #5
Opened 2022-08-23 14:56 UTC by devMunyi

-Added contact section which has:-
a heading, a description and the form itself

2022-08-23 17:25 UTC, ichala requested changes
Hi @devMunyi , 

Good job so far! 👏👏👏 
There are some issues that you still need to work on to go to the next project but you're almost there!

![the-simpsons-homer-simpson](https://user-images.githubusercontent.com/28307960/157369993-50d5ba12-099f-4f2a-9a19-5e57ee2d1c96.gif)

## To Highlight 🎉

- Great Design ✅ 
- Correct workflow ✅ 

 ## Required Changes ♻️

- [ ] **_Check the comments below_**

## Optional suggestions

N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-23 17:25 UTC, ichala commented on index.html
> +Write your message here
- [ ] the `Write your message here` should be a placeholder, kindly remove it from here and add it as a placeholder attribute for the `<textarea>`

2022-08-23 17:25 UTC, ichala commented on index.html
> +        action="https://formspree.io/html/"
- [ ] kindly create an account at [formspree](https://formspree.io/) to get an id for your submission link, currently `https://formspree.io/html/` the `html` is not an id generated by formspree, so your form will not post the data the id should look like `https://formspree.io/xbs64f` (please do not use it it's just an example and you should get your own id )

2022-08-23 17:25 UTC, ichala commented on index.html
> +        <button type="submit" class="contact-btn">Get It Touch</button>
- [ ] kindly make sure your button matches the Figma design and add the necessary hover, click and hover animations

![image](https://user-images.githubusercontent.com/89282221/186224583-9503331b-cf79-41fc-a620-e0effcf84c95.png)

2022-08-23 18:45 UTC, vickymarz requested changes
Hi @devMunyi , 

Great work on making the changes requested by a previous reviewer 👏 🔥 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![](https://camo.githubusercontent.com/56bcd754643682fcc078b66eaa7278dead6c9c5013595c875b4ddcbe0f0ef0aa/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f78554f786668365a4d373565664d3342716f2f67697068792d646f776e73697a65642d6d656469756d2e676966)

## Top highlight 🎯

- The PR title and description are professional and descriptive ✅ 
- The commit messages are meaningful ✅ 
- Linters are working properly ✅ 


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-23 18:45 UTC, vickymarz commented on index.html
> +        <button type="submit" class="contact-btn">Get In Touch</button>
- [ ] As the previous reviewer suggested, kindly implement the button interactions such as the pressed and hover effect

When I hover on your submit button, the background color should turn sky-blue while the text turns white just as it is in the Figma design. Kindly add it to make your webpage nicer 😄 

Your design 👇🏽 
![ezgif com-gif-maker](https://user-images.githubusercontent.com/63473584/186237847-2ada8017-6a6c-4966-9c24-848b1e6fb410.gif)

Figma Design 👇🏽 

![image](https://user-images.githubusercontent.com/63473584/186238737-01e70613-3bc7-4fbd-a13c-62847de05fff.png)

2022-08-24 05:05 UTC, BenMukebo requested changes
Hi @devMunyi, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

## To Highlight :clap: 
- No linter errors. :heavy_check_mark:
- GitHub flow is followed. :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good title and summary. ✔️


 ## Required Changes ♻️
_Check the comments under the review._


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

- [OPTIONAL] This is a group project. Please let's include all the authors in the README file. The Getting Started section and the License section of [this template](https://github.com/microverseinc/readme-template) are missing in your README file. Please let's make sure that all the main headers in the template are present in your README file. This makes the README file professional and descriptive. 


- [OPTIONAL]  Please let's make sure that contributions to a group project are distributed equally among the members (commit messages should be fairly equal).


Cheers and Happy coding!👏👏👏 💻  
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please Tag me on (@BenMukebo) when you comment so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-24 05:05 UTC, BenMukebo commented on index.html
> +      </form>
- [ ] Great job so far on your form 👏🏻 However there are one missing requirement, kindly make sure to address this:

- As requested by the previous reviewer [here](https://github.com/devMunyi/Portfolio/pull/5#discussion_r952993475). Button interactions such as hover, active (when it's pressed), disabled, and enable (default state) are styled as shown in the Figma template.
 - Please use this image below 👇🏻 to improve the background color of your  `Get In Touch` button 👍🏻 

![image](https://user-images.githubusercontent.com/79058364/186333331-cc91ebb0-aaa9-4d12-a5d0-c731326018f9.png)

2022-08-24 06:27 UTC, devMunyi commented on index.html
> +      </form>
@BenMukebo which color is this in CSS?

2022-08-24 07:14 UTC, Nemwel-Boniface approved these changes
## Hello @devMunyi               :wave: ,
I am Nemwel your reviewer for this PR :man_beard:  

Thank you for making the changes requested by the previous reviewer good job! :partying_face: 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! :partying_face: 🎉 

![](https://media.giphy.com/media/3kuSo744UIPJjcJUEn/giphy.gif)

## Highlights

Great job setting up the correct linters ✔️ 
Professional documentation ✔️ 
Correct workflow ✔️ 
Meaningful commit messages ✔️ 
Met all the milestone requirements ✔️ 

## [Optional] suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me **@Nemwel-Boniface** in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-24 07:34 UTC, merged

2022-08-24 13:54 UTC, BenMukebo commented on index.html
> +      </form>
Hello @devMunyi, Sorry for the late reply, I can see that you made the changes already. Congratulations 🎊